import type { Metadata } from "next";
import { Poppins, Bangers } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ChartColumnBigIcon } from "lucide-react";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

import { Button } from "@/components/ui/button";
import UserDropdown from "../components/userDropdown";
import { Toaster } from "sonner";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bangers",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link
              href="/"
              className="font-bold text-2xl flex items-center gap-1"
            >
              <ChartColumnBigIcon className="text-lime-500" />
              NextCash
            </Link>
            <div>
              <SignedOut>
                <div className="flex items-center  gap-1">
                  <Button
                    asChild
                    variant={"link"}
                    className="text-white cursor-pointer"
                  >
                    <SignInButton />
                  </Button>
                  <Button
                    asChild
                    variant={"link"}
                    className="text-white cursor-pointer"
                  >
                    <SignUpButton />
                  </Button>
                </div>
              </SignedOut>
              <SignedIn>
                <UserDropdown />
              </SignedIn>
            </div>
          </nav>
          {children}
          <Toaster richColors position="bottom-right" />
        </body>
      </html>
    </ClerkProvider>
  );
}
